query Invitation($code: String!) {
  getInvitation(invitationCode: $code) {
    id
    email
    firstName
    lastName
  }
}

query GetResetTokenInfo($token: String!) {
  getResetToken(resetToken: $token) {
    id
    userId
  }
}

mutation ForgotPassword($userName: String!) {
  forgotPassword(userName: $userName)
}

mutation Claim($code: String!, $password: String!) {
  claimInvitation(inviteCode: $code, password: $password)
}

mutation ResetPassword($token: String!, $newPassword: String!) {
  resetPassword(resetToken: $token, newPassword: $newPassword)
}
